/* soapINVPTransactionProcessorProxy.cpp
   Generated by gSOAP 2.8.32 for CyberSourceTransaction_nvp_1.129.h

gSOAP XML Web services tools
Copyright (C) 2000-2016, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#include "soapINVPTransactionProcessorProxy.h"

INVPTransactionProcessorProxy::INVPTransactionProcessorProxy()
{	this->soap = soap_new();
	this->soap_own = true;
	INVPTransactionProcessorProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

INVPTransactionProcessorProxy::INVPTransactionProcessorProxy(const INVPTransactionProcessorProxy& rhs)
{	this->soap = rhs.soap;
	this->soap_own = false;
	this->soap_endpoint = rhs.soap_endpoint;
}

INVPTransactionProcessorProxy::INVPTransactionProcessorProxy(struct soap *_soap)
{	this->soap = _soap;
	this->soap_own = false;
	INVPTransactionProcessorProxy_init(_soap->imode, _soap->omode);
}

INVPTransactionProcessorProxy::INVPTransactionProcessorProxy(const char *endpoint)
{	this->soap = soap_new();
	this->soap_own = true;
	INVPTransactionProcessorProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
	soap_endpoint = endpoint;
}

INVPTransactionProcessorProxy::INVPTransactionProcessorProxy(soap_mode iomode)
{	this->soap = soap_new();
	this->soap_own = true;
	INVPTransactionProcessorProxy_init(iomode, iomode);
}

INVPTransactionProcessorProxy::INVPTransactionProcessorProxy(const char *endpoint, soap_mode iomode)
{	this->soap = soap_new();
	this->soap_own = true;
	INVPTransactionProcessorProxy_init(iomode, iomode);
	soap_endpoint = endpoint;
}

INVPTransactionProcessorProxy::INVPTransactionProcessorProxy(soap_mode imode, soap_mode omode)
{	this->soap = soap_new();
	this->soap_own = true;
	INVPTransactionProcessorProxy_init(imode, omode);
}

INVPTransactionProcessorProxy::~INVPTransactionProcessorProxy()
{	if (this->soap_own)
		soap_free(this->soap);
}

void INVPTransactionProcessorProxy::INVPTransactionProcessorProxy_init(soap_mode imode, soap_mode omode)
{	soap_imode(this->soap, imode);
	soap_omode(this->soap, omode);
	soap_endpoint = NULL;
	static const struct Namespace namespaces[] = {
        {"SOAP-ENV", "http://schemas.xmlsoap.org/soap/envelope/", "http://www.w3.org/*/soap-envelope", NULL},
        {"SOAP-ENC", "http://schemas.xmlsoap.org/soap/encoding/", "http://www.w3.org/*/soap-encoding", NULL},
        {"xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL},
        {"xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL},
        {"c14n", "http://www.w3.org/2001/10/xml-exc-c14n#", NULL, NULL},
        {"wsu", "http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd", NULL, NULL},
        {"xenc", "http://www.w3.org/2001/04/xmlenc#", NULL, NULL},
        {"wsc", "http://docs.oasis-open.org/ws-sx/ws-secureconversation/200512", NULL, NULL},
        {"ds", "http://www.w3.org/2000/09/xmldsig#", NULL, NULL},
        {"wsse", "http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd", "http://docs.oasis-open.org/wss/oasis-wss-wssecurity-secext-1.1.xsd", NULL},
        {"ns2", "urn:schemas-cybersource-com:transaction-data-1.129", NULL, NULL},
        {"ns1", "urn:schemas-cybersource-com:transaction-data:TransactionProcessor", NULL, NULL},
        {NULL, NULL, NULL, NULL}
    };
	soap_set_namespaces(this->soap, namespaces);
}

#ifndef WITH_PURE_VIRTUAL
INVPTransactionProcessorProxy *INVPTransactionProcessorProxy::copy()
{	INVPTransactionProcessorProxy *dup = SOAP_NEW_COPY(INVPTransactionProcessorProxy);
	if (dup)
		soap_copy_context(dup->soap, this->soap);
	return dup;
}
#endif

INVPTransactionProcessorProxy& INVPTransactionProcessorProxy::operator=(const INVPTransactionProcessorProxy& rhs)
{	if (this->soap_own)
		soap_free(this->soap);
	this->soap = rhs.soap;
	this->soap_own = false;
	this->soap_endpoint = rhs.soap_endpoint;
	return *this;
}

void INVPTransactionProcessorProxy::destroy()
{	soap_destroy(this->soap);
	soap_end(this->soap);
}

void INVPTransactionProcessorProxy::reset()
{	this->destroy();
	soap_done(this->soap);
	soap_initialize(this->soap);
	INVPTransactionProcessorProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

void INVPTransactionProcessorProxy::soap_noheader()
{	this->soap->header = NULL;
}

void INVPTransactionProcessorProxy::soap_header(struct _wsse__Security *wsse__Security)
{	::soap_header(this->soap);
	this->soap->header->wsse__Security = wsse__Security;
}

::SOAP_ENV__Header *INVPTransactionProcessorProxy::soap_header()
{	return this->soap->header;
}

::SOAP_ENV__Fault *INVPTransactionProcessorProxy::soap_fault()
{	return this->soap->fault;
}

const char *INVPTransactionProcessorProxy::soap_fault_string()
{	return *soap_faultstring(this->soap);
}

const char *INVPTransactionProcessorProxy::soap_fault_detail()
{	return *soap_faultdetail(this->soap);
}

int INVPTransactionProcessorProxy::soap_close_socket()
{	return soap_closesock(this->soap);
}

int INVPTransactionProcessorProxy::soap_force_close_socket()
{	return soap_force_closesock(this->soap);
}

void INVPTransactionProcessorProxy::soap_print_fault(FILE *fd)
{	::soap_print_fault(this->soap, fd);
}

#ifndef WITH_LEAN
#ifndef WITH_COMPAT
void INVPTransactionProcessorProxy::soap_stream_fault(std::ostream& os)
{	::soap_stream_fault(this->soap, os);
}
#endif

char *INVPTransactionProcessorProxy::soap_sprint_fault(char *buf, size_t len)
{	return ::soap_sprint_fault(this->soap, buf, len);
}
#endif

int INVPTransactionProcessorProxy::runTransaction(const char *endpoint, const char *soap_action, wchar_t *ns2__nvpRequest, wchar_t *&ns2__nvpReply)
{	struct soap *soap = this->soap;
	struct __ns1__runTransaction soap_tmp___ns1__runTransaction;
	struct __ns1__runTransactionResponse *soap_tmp___ns1__runTransactionResponse;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_endpoint == NULL)
		soap_endpoint = "https://ics2wsa.ic3.com:443/commerce/1.x/transactionProcessor";
	if (soap_action == NULL)
		soap_action = "runTransaction";
	soap_tmp___ns1__runTransaction.ns2__nvpRequest = ns2__nvpRequest;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__runTransaction(soap, &soap_tmp___ns1__runTransaction);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__runTransaction(soap, &soap_tmp___ns1__runTransaction, "-ns1:runTransaction", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__runTransaction(soap, &soap_tmp___ns1__runTransaction, "-ns1:runTransaction", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	ns2__nvpReply = NULL;
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_tmp___ns1__runTransactionResponse = soap_get___ns1__runTransactionResponse(soap, NULL, "-ns1:runTransactionResponse", NULL);
	if (!soap_tmp___ns1__runTransactionResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	ns2__nvpReply = soap_tmp___ns1__runTransactionResponse->ns2__nvpReply;
	return soap_closesock(soap);
}
/* End of client proxy code */
